spring.application.name=govnext-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/govnext_db
spring.datasource.username=postgres
spring.datasource.password=vedant

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080