package com.govnext.backend.repository;

import com.govnext.backend.entity.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;

@Repository
public interface UserRepository extends JpaRepository<User, Long> {
    // Custom finder query automatically generated by Spring Data JPA
    Optional<User> findByEmail(String email);
}